#!/bin/bash
TARGET_DIR="public/sounds"
mkdir -p "$TARGET_DIR"
BASE64_STR="SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjU5LjE2LjEwMAAAAAAAAAAAAAAA//OEAAAAAAAAAAAAAAAAAAAAAAAASW5mbwAAAA8AAAAFAAAARgAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQ/////////////////////////////////////wAAADhMYXZjNTkuMTguMTAwAAAAAAAAAAAAAAACRAAAPeA38YJRAAAARgAAAAAA//MUxAAAAANIAMIAAAAq4ABCAAAATzE0MwwAAAAAIgAAAAAAbgBwAAcKBAAHCw4ICwwIBQYCBQYCBQUHBQUFAwMDAwIICAkKCQsLCgsLCgoJCQkKCgkDAwMDAwMDAwMHBwYGBgYFBAQFBQUFBwYHBgcHBwcJCAgICQkKCgoLDAwNDQ4PDw8PDw8ODg4NDAwLCgkIBwUEAgIAAQEBCAgAAAAAAAAP/zDEsAAu0CxgDCAAAKpAALAAAAAnB5ZDAAAAEAAAAAAQAAAAAABwYGBAQGBwYEAwICAQECAwMDBQUHBwcJCQsLDA0NDg8QEBEA/8wxO0AL2AoQAwgAACgwAAAAAAAJ/zDE4oAuYCwwDCAAAKzAAAAAAAJ/zDE1AAuYCxADCAAAK/AAAAAAAJ//OExLQABQAAABgAAAQAAAAABAAACf/zDErQAuYCyADCAAAK9AAAAAAAJ/zDEuQAuYCzADCAAAK/AAAAAAAJ/zDEvAAuYC0ADCAAAK9AAAAAAAJ/zDEuwAuYC1ADCAAAKzAAAAAAAJ"

echo "$BASE64_STR" | base64 -D > "$TARGET_DIR/success.mp3"
echo "$BASE64_STR" | base64 -D > "$TARGET_DIR/error.mp3"
echo "$BASE64_STR" | base64 -D > "$TARGET_DIR/approval.mp3"
echo "$BASE64_STR" | base64 -D > "$TARGET_DIR/lead.mp3"
echo "$BASE64_STR" | base64 -D > "$TARGET_DIR/notification.mp3"
echo "Binary dummy sounds written."
